name: Nightly Build

on:
  schedule:
    # Every day at 6:11 AM UTC or 2:11 AM EST
    - cron: '11 6 * * *'
  pull_request:
    paths:
     - .github/workflows/Nightly.yml
  workflow_dispatch:

# Set minimal permissions for all jobs (read-only)
permissions:
  contents: read
  actions: read

jobs:
  tag-latest:
    if: ( github.repository == 'SimpleITK/SimpleITK' ) &&  ( github.event_name == 'schedule' )
    runs-on: ubuntu-latest
    # Needs write permissions for contents and actions to tag and trigger workflows
    permissions:
      contents: write
      actions: write
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Check if latest tag is up to date
        id: check_latest
        run: |
          if [ "$(git rev-parse ${{github.event.repository.default_branch}})" = "$(git rev-parse latest)" ]; then
            echo "uptodate=true" >> $GITHUB_OUTPUT
          else
            echo "uptodate=false" >> $GITHUB_OUTPUT
          fi

      - name: Tag latest and trigger Package workflow
        if: steps.check_latest.outputs.uptodate == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "updating latest tag"
          git tag -f latest
          git push origin -f latest

          gh workflow run Package --ref latest

          echo "### Updated latest tag and triggered Package workflow" >> $GITHUB_STEP_SUMMARY

      - name: Latest is up to date
        if: steps.check_latest.outputs.uptodate == 'true'
        run: echo "### Latest is uptodate." >> $GITHUB_STEP_SUMMARY
  matrix-jobs:
    if: github.repository == 'SimpleITK/SimpleITK'
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.name }}
    strategy:
      matrix:
        include:

          - os: codebuild-SimpleITK-${{ github.run_id }}-${{ github.run_attempt }}-ubuntu-7.0-xlarge
            name: coverage
            cmake-build-type: "RelWithDebInfo"
            ctest-cache: |
              CMAKE_CXX_FLAGS:STRING=-g -O0 --coverage
              CMAKE_C_FLAGS:STRING=-g -O0 --coverage
              CMAKE_EXE_LINKER_FLAGS:STRING=-g -O0 -lgcov
              CTEST_CUSTOM_COVERAGE_EXCLUDE:STRING=".*/ITK-prefix/.*" ".*/GTest-prefix/.*"
            ctest-extra-args: |
              -Ddashboard_do_coverage=1 \
              -Ddashboard_track="Nightly" \
              -DCTEST_COVERAGE_COMMAND="$(which gcov)"

          - os: codebuild-SimpleITK-${{ github.run_id }}-${{ github.run_attempt }}-ubuntu-7.0-xlarge
            name: valgrind
            cmake-build-type: "RelWithDebInfo"
            apt-get-dependencies: "valgrind"
            ctest-test-timeout: 10000
            ctest-extra-args: |
              -Ddashboard_do_memcheck=1 \
              -Ddashboard_track="Nightly" \
              -DCTEST_MEMORYCHECK_COMMAND="$(type -p valgrind)" \
              -DCTEST_MEMORYCHECK_COMMAND_OPTIONS="--trace-children=yes --quiet --tool=memcheck --leak-check=yes --show-reachable=yes --num-callers=50 --verbose --demangle=yes --gen-suppressions=all  --child-silent-after-fork=yes" \
              -DCTEST_MEMORYCHECK_SUPPRESSIONS_FILE="${CTEST_SOURCE_DIRECTORY}/CMake/Valgrind-Ubuntu2004.supp"

    env:
      CTEST_SOURCE_DIRECTORY: "${{ github.workspace }}"
      CTEST_BINARY_DIRECTORY: "${{ github.workspace }}/bld"
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: "${{ github.event.pull_request.head.sha }}"
      - uses: actions/checkout@v5
        with:
          path: SimpleITK-dashboard
          ref: dashboard
      - name: Generate External Data Hash
        shell: bash
        run: |
          git log -n 1 "${{ github.workspace }}/Testing/Data/" | tee "${{ github.workspace }}/external-data.hashable"
      - uses: actions/cache@v4
        id: cache
        with:
          path: ${{ runner.temp }}/.ExternalData
          key: external-data-v1-${{ hashFiles( format( '{0}/{1}', github.workspace, 'external-data.hashable') ) }}
          enableCrossOsArchive: true
          restore-keys: |
            external-data-v1-
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        id: cpy
        with:
          python-version: 3.11

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r ./.github/workflows/requirements-build.txt

          if [ ! -z "${{ matrix.apt-get-dependencies }}" ]; then
            sudo apt-get update
            sudo apt-get install -y ${{ matrix.apt-get-dependencies }}
          fi
      - name: Build and Test
        shell: bash
        env:
          DASHBOARD_BRANCH_DIRECTORY: "${{ github.workspace }}/SimpleITK-dashboard"
          ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS: 2
          CTEST_CONFIGURATION_TYPE: ${{ matrix.cmake-build-type }}
          CTEST_CMAKE_GENERATOR: "Ninja"
          CTEST_OUTPUT_ON_FAILURE: 1
          CTEST_TEST_TIMEOUT: ${{ matrix.ctest-test-timeout }}
          CTEST_CACHE: |
            WRAP_DEFAULT:BOOL=OFF
            BUILD_EXAMPLES:BOOL=ON
            BUILD_TESTING:BOOL=ON
            ${{ matrix.ctest-cache }}

        run: |
          cmake --version
          gcov --version
          ctest -S ${CTEST_SOURCE_DIRECTORY}/.github/workflows/github_actions.cmake -V \
            ${{ matrix.ctest-extra-args }}
