name: Python Lint and Spell Checking

on:
  push:
    branches: [ master, main, release ]
  pull_request:
    branches: [ master, main, release ]

jobs:

  #  The 'lint' job runs pre-commit hooks to check for various code quality issues
  #  including linting, spell checking, and formatting.
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - run: python -m pip install pre-commit
        shell: bash
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-3|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
      - run: pre-commit run --show-diff-on-failure --color=always --all-files
        shell: bash
